version: "3"

services:
  mongoDB:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  elas-backend:
    image: elas-backend
    build: ./backend
    restart: unless-stopped
    environment: 
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app:ro
    depends_on:
      - mongoDB
    networks:
      - backend
      - frontend

  elas-frontend:
    image: elas-frontend
    build: ./frontend
    restart: unless-stopped
    stdin_open: true
    environment: 
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:ro
    depends_on:
      - elas-backend
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
