courseInsightsTargetFile: /app/bin/studyprograms.js
courseScraper: /app/uni-due-course-catalog-scraper/
e3RatingsFile: /app/bin/avg_ratings.json
e3TargetFile: /app/bin/e3_courses.json
ratingsEmail:
ratingsPassword:
ratingsScraper: /app/course-ratings/
statusMessage: 2021-08-26 10:43
